#!/usr/bin/env python3
"""Creates lib/firebase_options.dart from android/app/google-services.json.

    cd customer_app
    python3 tools/gen_firebase_options.py

Re-run it whenever you download a new google-services.json (for example
after adding SHA fingerprints or enabling Google sign-in).
"""
import json
import os
import sys

PACKAGE = 'com.dripzzee.customer_app'
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, 'android', 'app', 'google-services.json')
OUT = os.path.join(ROOT, 'lib', 'firebase_options.dart')

if not os.path.exists(SRC):
    sys.exit('✗ android/app/google-services.json not found. Download it from '
             'Firebase console → Project settings → Your apps → Android app.')

g = json.load(open(SRC))
p = g['project_info']
clients = [c for c in g.get('client', [])
           if c['client_info']['android_client_info']['package_name'] == PACKAGE]
if not clients:
    sys.exit(f'✗ google-services.json has no Android app for {PACKAGE}.')
c = clients[0]

web_ids = [o['client_id'] for o in c.get('oauth_client', [])
           if o.get('client_type') == 3]
invite = c.get('services', {}).get('appinvite_service', {})
web_ids += [o['client_id'] for o in invite.get('other_platform_oauth_client', [])
            if o.get('client_type') == 3]
android_oauth = [o for o in c.get('oauth_client', []) if o.get('client_type') == 1]
web_id = web_ids[0] if web_ids else ''

open(OUT, 'w').write(f"""// Generated by tools/gen_firebase_options.py from
// android/app/google-services.json — do not edit by hand.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {{
  static FirebaseOptions get currentPlatform => android;

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '{c['api_key'][0]['current_key']}',
    appId: '{c['client_info']['mobilesdk_app_id']}',
    messagingSenderId: '{p['project_number']}',
    projectId: '{p['project_id']}',
    storageBucket: '{p.get('storage_bucket', '')}',
  );

  /// OAuth "Web client" ID — used by native Google sign-in.
  static const googleWebClientId = '{web_id}';
}}
""")

print(f"✓ lib/firebase_options.dart written for {p['project_id']}")
if web_id:
    print('✓ Google web client ID found')
else:
    print('! No Google web client ID in google-services.json — enable Google in '
          'Authentication → Sign-in method, then download the file again.')
if android_oauth:
    print(f'✓ {len(android_oauth)} SHA fingerprint(s) registered for Android')
else:
    print('! No SHA fingerprints registered — add SHA-1 and SHA-256 in Project '
          'settings → Your apps, then download the file again.')
